---
title: "Crosstab on LGBTQIA+ and race by psychological distress"
author: "Alicia Vo"
date: "2025-04-04"
output: html_document
---

```{r}
library(tidyverse)
library(srvyr)
library(RPostgres)
library(ggplot2)
library(dplyr)
library(forcats)

# Get function cross_tab_df()
source("./crosstab_svyquestions.R")

# Used to get RDA function for adding table comments
source("W:\\RDA Team\\R\\Github\\RDA Functions\\main\\RDA-Functions\\Utility_Functions.R")

# Connect to postgres
source("W:\\RDA Team\\R\\credentials_source.R")
con <- connect_to_db("bold_vision")

# Pull in the survey data and data dictionary
raw_svy_data <- dbGetQuery(con, "SELECT * FROM youth_thriving.raw_survey_data")
svy_dd <- dbGetQuery(con, "SELECT * FROM youth_thriving.bvys_datadictionary_2024")

# Pull in LGBTQIA+ and race data
gender_sexuality_data <- dbGetQuery(con, "SELECT response_id, cishet_lgbtqia FROM youth_thriving.gender_sexuality_data")
race_ethnicity_data <- dbGetQuery(con, "SELECT response_id, nh_race FROM youth_thriving.race_ethnicity_data")

# Merge SOGI and race data frames into svy_data using response_id
svy_data <- raw_svy_data %>%
  left_join(gender_sexuality_data, by = "response_id") %>%
  left_join(race_ethnicity_data, by = "response_id") 
```

```{r}
# Clean up data to prep for crosstab of race and lgbtqia by psych distress
race_lgbtqia_data <- svy_data %>%
  select(response_id, nh_race, cishet_lgbtqia, cy, weights_final) %>%
  filter(!nh_race %in% c("do_not_wish", "NA"), !is.na(nh_race), !is.na(cishet_lgbtqia), !is.na(cy)) 

# Check unique values of columns nh_race and cy (psych distress question)
qa_check <- lapply(race_lgbtqia_data[,c("nh_race","cy")], unique)

# Create column cy_binary where respondents who answer None of the time to a psych distress question are labelled as 0. Otherwise, the respondent is labelled as 1. We're combining responses because the sample sizes are too small.
race_lgbtqia_data <- race_lgbtqia_data %>%
  mutate(race_lgbtqia = paste(nh_race, ifelse(cishet_lgbtqia == 0, "& cisgender heterosexual", "& LGBTQIA+")),
         cy_binary = ifelse(cy==1,0,1))

# Frequency table for race groups and lgbtqia+. Counts are too low (less than 5 respondents) for nh_aian, nh_other, nh_nhpi 
freq_race_lgbtqia <- race_lgbtqia_data %>% as_survey_design(weights = weights_final) %>%
  group_by(race_lgbtqia) %>%
  summarise(count = survey_total(),
            rate = survey_prop()) %>% # Automatically ensures sum = 100%
  mutate(rate = rate * 100,
         rate_se = rate_se * 100) %>%  # Convert to percentages
  ungroup()

# Crosstab table for race groups and lgbtqia+ by a psych distress question.
crosstab_race_lgbtqia <- race_lgbtqia_data %>% as_survey_design(weights = weights_final) %>%
  group_by(race_lgbtqia, cy) %>%
  summarise(count = survey_total(),
            rate = survey_prop()) %>% # Automatically ensures sum = 100%
  mutate(rate = rate * 100,
         rate_se = rate_se * 100) %>%  # Convert to percentages
  ungroup()

# Crosstab table for race groups by lgbtqia+ and a REVISED binary psych distress question.
crosstab_race_lgbtqia_binary <- race_lgbtqia_data %>% as_survey_design(weights = weights_final) %>%
  filter(!nh_race %in% c("nh_aian", "nh_other", "nh_nhpi")) %>%
  group_by(race_lgbtqia, cy_binary) %>%
  summarise(count = survey_total(),
            rate = survey_prop()) %>% # Automatically ensures sum = 100%
  mutate(rate = rate * 100,
         rate_se = rate_se * 100) %>%  # Convert to percentages
  ungroup()
```

```{r}
# Only plot groups who respond as feeling worthless in the past 30 days and order the bars in descending order
plot_data <- crosstab_race_lgbtqia_binary %>%
  filter(cy_binary == 1) %>%
  mutate(race_lgbtqia = fct_reorder(race_lgbtqia, rate))

ggplot(plot_data, aes(x = race_lgbtqia, y = rate)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = paste0("   = ", round(count,0))), hjust = -0.1, size = 3) + 
  coord_flip() +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +  # Add space on the right
  theme_minimal() +
  guides(fill = "none") +
  labs(x = NULL, y = "Rate of Feeling of Worthless in the Past 30 Days (%)")
```

```{r}
# Join data dictionary to crosstab  
var1 <- "cy"

dict <- svy_dd %>%
  filter(variable == var1) %>%
  pivot_longer(cols = response_1:response_12,
               names_to = "response_numbers",
               values_to = "response",
               values_drop_na = TRUE)
dict_var <- dict %>%
  mutate(
    response_number = as.numeric(str_extract(response_numbers, "\\d+")))  # Extract the number and convert to numeric

dict_var1 <- dict_var %>%
  filter(variable == var1) %>%
  select(response_number, response, question, sub_question, response_domain, variable_name) %>%
  rename(response_var1 = response,
         component_var1 = response_domain,
         subcomponent_var1 = variable_name,
         question_var1 = question,
         sub_question_var1 = sub_question)

crosstab_race_lgbtqia <- crosstab_race_lgbtqia %>%
  left_join(dict_var1, by = setNames("response_number", var1))
```
