---
title: Bold Vision Youth Thriving Survey 
subtitle: Frequencies and Trends by Question and Category
output:
  html_document:
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)

### Step 1: Environment set up ----

library(data.table)
library(dplyr)
library(RPostgreSQL)
library(sf)
library(tidyr)
library(readxl)
library(tidyverse)
library(janitor)
library(srvyr)
library(survey)
library(highcharter)
library(knitr)
library(kableExtra)
options(scipen=999)

# connect to postgres
source("W:\\RDA Team\\R\\credentials_source.R")
con <- connect_to_db("bold_vision")

### Step 2: Pull in and prep data ----
svy_df <- dbGetQuery(con, "SELECT * FROM youth_thriving.raw_survey_data")
svy_dd <- dbGetQuery(con, "SELECT * FROM youth_thriving.bvys_datadictionary_2024 WHERE response_type = 'mc'")

# Descriptive Function -----
question_sum<-function (svy_df,svy_dd,domain,variable) {
df <- svy_dd%>%filter(response_domain=="domain" & variable_name=="variable")

unique_vars <- unique(df$variable)

all_vars_df<-NULL

for (i in unique_vars) {

  dict <- df %>% filter(variable == i) %>%
    pivot_longer(cols = response_1: response_12,
                 names_to = "response_numbers",
                 values_to = "response",
                 values_drop_na = TRUE)

  dict_var <- dict %>%
    mutate(variable_merge_col = 1:nrow(dict))

  df_var<-svy_df%>%as_survey(weights=c(weights_final))%>%
    filter(!is.na(!!as.symbol(i)))%>%
    group_by(!!rlang::ensym(i))%>%
    summarise(frequency=n(),percent=survey_mean(vartype="cv",level=.90))%>%
    mutate(percent=percent*100,percent_cv=percent_cv*100)%>%
    rename(weighted_percent=percent)

  df_final <-  merge(x = df_var, y = dict_var, by.x = c(i), by.y = c("variable_merge_col"))%>%
    select(question,sub_question,response,frequency,weighted_percent,percent_cv)
 
  df_table<-df_final%>%rename_with(toupper)%>%rename(PERCENT=WEIGHTED_PERCENT)
  colnames(df_table)<-gsub("_", " ", colnames(df_table))
  
 visual <- kable(as.data.frame(df_table)%>% 
   mutate_if(is.numeric, format, digits=2)) %>%
  kable_styling("striped", full_width = F) %>%
  row_spec(0, background = "#2A12B2", color = "white",font_size=12)%>%
   footnote(general="Frequencies are unweighted counts. Percentages and coefficients of variation (CV) are weighted")


  print(visual) 
  
  all_vars_df<-rbind(all_vars_df,df_final)

}
}


```


# Strong Minds
## Positive Emotions
```{r, message = FALSE, results='asis'}

question_sum(svy_df,svy_dd,domain="Strong Minds",variable="Positive Emotions")


question_sum(svy_df,svy_dd,domain="Strong Minds",variable="Growth Mindset")

  

dd_filter <- dbGetQuery(con, "SELECT * FROM youth_thriving.bvys_datadictionary_2024 WHERE response_type = 'mc' AND response_domain = 'Strong Minds'")

unique_indicators <- unique(dd_filter$variable)

knitr::opts_chunk$set(echo = FALSE)
#### Step 3: Run Loop Funcion to produce tables ####
for (var_string in unique_indicators) {

  dict <- dd_filter %>% filter(variable == var_string) %>%
    pivot_longer(cols = response_1: response_12,
                 names_to = "responses",
                 values_to = paste0(var_string, "_labels"),
                 values_drop_na = TRUE)

  dict_var <- dict %>%
    mutate(variable_merge_col = 1:nrow(dict))


  df_var <- as_survey(svy_data, weights = weights_final) %>%
    group_by(!!rlang::ensym(var_string)) %>%
    summarise(frequency = n()) %>%
    mutate(percent = round(frequency/sum(frequency)*100, 1))

  df_final <-  merge(x = df_var, y = dict_var, by.x = c(var_string), by.y = c("variable_merge_col")) %>%
    relocate(paste0(var_string, "_labels")) %>% select(1, 3:8)

  visual <- print(kable(as.data.frame(df_final), "html") %>%
  kable_styling("striped", full_width = F) %>%
  row_spec(0, background = "#5E17EB", color = "white")) 

  print(visual) 

}

```

# Positive Identity And Self-Worth

```{r, message = FALSE, results='asis'}

dd_filter <- dbGetQuery(con, "SELECT * FROM youth_thriving.bvys_datadictionary_2024 WHERE response_type = 'mc' AND response_domain = 'Positive Identity and Self-Worth'")

unique_indicators <- unique(dd_filter$variable)

knitr::opts_chunk$set(echo = FALSE)
#### Step 3: Run Loop Funcion to produce tables ####
for (var_string in unique_indicators) {

  dict <- dd_filter %>% filter(variable == var_string) %>%
    pivot_longer(cols = response_1: response_12,
                 names_to = "responses",
                 values_to = paste0(var_string, "_labels"),
                 values_drop_na = TRUE)

  dict_var <- dict %>%
    mutate(variable_merge_col = 1:nrow(dict))


  df_var <- as_survey(svy_data, weights = weights_final) %>%
    group_by(!!rlang::ensym(var_string)) %>%
    summarise(frequency = n()) %>%
    mutate(percent = round(frequency/sum(frequency)*100, 1))

  df_final <-  merge(x = df_var, y = dict_var, by.x = c(var_string), by.y = c("variable_merge_col")) %>%
    relocate(paste0(var_string, "_labels")) %>% select(1, 3:8)

  visual <- print(kable(as.data.frame(df_final), "html") %>%
  kable_styling("striped", full_width = F) %>%
  row_spec(0, background = "#5E17EB", color = "white"))


  print(visual) 

}

```

# Caring Families And Relationships

```{r, message = FALSE, results='asis'}

dd_filter <- dbGetQuery(con, "SELECT * FROM youth_thriving.bvys_datadictionary_2024 WHERE response_type = 'mc' AND response_domain = 'Caring Families And Relationships'")

unique_indicators <- unique(dd_filter$variable)

knitr::opts_chunk$set(echo = FALSE)
#### Step 3: Run Loop Funcion to produce tables ####
for (var_string in unique_indicators) {

  dict <- dd_filter %>% filter(variable == var_string) %>%
    pivot_longer(cols = response_1: response_12,
                 names_to = "responses",
                 values_to = paste0(var_string, "_labels"),
                 values_drop_na = TRUE)

  dict_var <- dict %>%
    mutate(variable_merge_col = 1:nrow(dict))


  df_var <- as_survey(svy_data, weights = weights_final) %>%
    group_by(!!rlang::ensym(var_string)) %>%
    summarise(frequency = n()) %>%
    mutate(percent = round(frequency/sum(frequency)*100, 1))

  df_final <-  merge(x = df_var, y = dict_var, by.x = c(var_string), by.y = c("variable_merge_col")) %>%
    relocate(paste0(var_string, "_labels")) %>% select(1, 3:8)

  visual <- print(kable(as.data.frame(df_final), "html") %>%
  kable_styling("striped", full_width = F) %>%
  row_spec(0, background = "#5E17EB", color = "white"))


  print(visual) 

}

```

# Positive Identity And Self-Worth

```{r, message = FALSE, results='asis'}

dd_filter <- dbGetQuery(con, "SELECT * FROM youth_thriving.bvys_datadictionary_2024 WHERE response_type = 'mc' AND response_domain = 'Positive Identity And Self-Worth'")

unique_indicators <- unique(dd_filter$variable)

knitr::opts_chunk$set(echo = FALSE)
#### Step 3: Run Loop Funcion to produce tables ####
for (var_string in unique_indicators) {

  dict <- dd_filter %>% filter(variable == var_string) %>%
    pivot_longer(cols = response_1: response_12,
                 names_to = "responses",
                 values_to = paste0(var_string, "_labels"),
                 values_drop_na = TRUE)

  dict_var <- dict %>%
    mutate(variable_merge_col = 1:nrow(dict))


  df_var <- as_survey(svy_data, weights = weights_final) %>%
    group_by(!!rlang::ensym(var_string)) %>%
    summarise(frequency = n()) %>%
    mutate(percent = round(frequency/sum(frequency)*100, 1))

  df_final <-  merge(x = df_var, y = dict_var, by.x = c(var_string), by.y = c("variable_merge_col")) %>%
    relocate(paste0(var_string, "_labels")) %>% select(1, 3:8)

  visual <- print(kable(as.data.frame(df_final), "html") %>%
  kable_styling("striped", full_width = F) %>%
  row_spec(0, background = "#5E17EB", color = "white"))

  print(visual) 

}

```

# Vibrant Communities

```{r, message = FALSE, results='asis'}

dd_filter <- dbGetQuery(con, "SELECT * FROM youth_thriving.bvys_datadictionary_2024 WHERE response_type = 'mc' AND response_domain = 'Vibrant Communities'")

unique_indicators <- unique(dd_filter$variable)

knitr::opts_chunk$set(echo = FALSE)
#### Step 3: Run Loop Funcion to produce tables ####
for (var_string in unique_indicators) {

  dict <- dd_filter %>% filter(variable == var_string) %>%
    pivot_longer(cols = response_1: response_12,
                 names_to = "responses",
                 values_to = paste0(var_string, "_labels"),
                 values_drop_na = TRUE)

  dict_var <- dict %>%
    mutate(variable_merge_col = 1:nrow(dict))


  df_var <- as_survey(svy_data, weights = weights_final) %>%
    group_by(!!rlang::ensym(var_string)) %>%
    summarise(frequency = n()) %>%
    mutate(percent = round(frequency/sum(frequency)*100, 1))

  df_final <-  merge(x = df_var, y = dict_var, by.x = c(var_string), by.y = c("variable_merge_col")) %>%
    relocate(paste0(var_string, "_labels")) %>% select(1, 3:8)

  visual <- print(kable(as.data.frame(df_final), "html") %>%
  kable_styling("striped", full_width = F) %>%
  row_spec(0, background = "#5E17EB", color = "white"))

  print(visual) 

}

```

# Cultural Identity

```{r, message = FALSE, results='asis'}

dd_filter <- dbGetQuery(con, "SELECT * FROM youth_thriving.bvys_datadictionary_2024 WHERE response_type = 'mc' AND response_domain = 'Cultural Identity'")

unique_indicators <- unique(dd_filter$variable)

knitr::opts_chunk$set(echo = FALSE)
#### Step 3: Run Loop Funcion to produce tables ####
for (var_string in unique_indicators) {

  dict <- dd_filter %>% filter(variable == var_string) %>%
    pivot_longer(cols = response_1: response_12,
                 names_to = "responses",
                 values_to = paste0(var_string, "_labels"),
                 values_drop_na = TRUE)

  dict_var <- dict %>%
    mutate(variable_merge_col = 1:nrow(dict))


  df_var <- as_survey(svy_data, weights = weights_final) %>%
    group_by(!!rlang::ensym(var_string)) %>%
    summarise(frequency = n()) %>%
    mutate(percent = round(frequency/sum(frequency)*100, 1))

  df_final <-  merge(x = df_var, y = dict_var, by.x = c(var_string), by.y = c("variable_merge_col")) %>%
    relocate(paste0(var_string, "_labels")) %>% select(1, 3:8)

  visual <- print(kable(as.data.frame(df_final), "html") %>%
  kable_styling("striped", full_width = F) %>%
  row_spec(0, background = "#5E17EB", color = "white"))

  print(visual) 

}

```
# Interrelated Domain

```{r, message = FALSE, results='asis'}

dd_filter <- dbGetQuery(con, "SELECT * FROM youth_thriving.bvys_datadictionary_2024 WHERE response_type = 'mc' AND response_domain = 'Interrelated Domain'")

unique_indicators <- unique(dd_filter$variable)

knitr::opts_chunk$set(echo = FALSE)
#### Step 3: Run Loop Funcion to produce tables ####
for (var_string in unique_indicators) {

  dict <- dd_filter %>% filter(variable == var_string) %>%
    pivot_longer(cols = response_1: response_12,
                 names_to = "responses",
                 values_to = paste0(var_string, "_labels"),
                 values_drop_na = TRUE)

  dict_var <- dict %>%
    mutate(variable_merge_col = 1:nrow(dict))


  df_var <- as_survey(svy_data, weights = weights_final) %>%
    group_by(!!rlang::ensym(var_string)) %>%
    summarise(frequency = n()) %>%
    mutate(percent = round(frequency/sum(frequency)*100, 1))

  df_final <-  merge(x = df_var, y = dict_var, by.x = c(var_string), by.y = c("variable_merge_col")) %>%
    relocate(paste0(var_string, "_labels")) %>% select(1, 3:8)

  visual <- print(kable(as.data.frame(df_final), "html") %>%
  kable_styling("striped", full_width = F) %>%
  row_spec(0, background = "#5E17EB", color = "white"))

  print(visual) 

}

```

# Racial Justice, Equity, And Inclusion

```{r, message = FALSE, results='asis'}

dd_filter <- dbGetQuery(con, "SELECT * FROM youth_thriving.bvys_datadictionary_2024 WHERE response_type = 'mc' AND response_domain = 'Racial Justice, Equity, And Inclusion'")

unique_indicators <- unique(dd_filter$variable)

knitr::opts_chunk$set(echo = FALSE)
#### Step 3: Run Loop Funcion to produce tables ####
for (var_string in unique_indicators) {

  dict <- dd_filter %>% filter(variable == var_string) %>%
    pivot_longer(cols = response_1: response_12,
                 names_to = "responses",
                 values_to = paste0(var_string, "_labels"),
                 values_drop_na = TRUE)

  dict_var <- dict %>%
    mutate(variable_merge_col = 1:nrow(dict))


  df_var <- as_survey(svy_data, weights = weights_final) %>%
    group_by(!!rlang::ensym(var_string)) %>%
    summarise(frequency = n()) %>%
    mutate(percent = round(frequency/sum(frequency)*100, 1))

  df_final <-  merge(x = df_var, y = dict_var, by.x = c(var_string), by.y = c("variable_merge_col")) %>%
    relocate(paste0(var_string, "_labels")) %>% select(1, 3:8)

  visual <- print(kable(as.data.frame(df_final), "html") %>%
  kable_styling("striped", full_width = F) %>%
  row_spec(0, background = "#5E17EB", color = "white"))

  print(visual) 

}

```

# Safety

```{r, message = FALSE, results='asis'}

dd_filter <- dbGetQuery(con, "SELECT * FROM youth_thriving.bvys_datadictionary_2024 WHERE response_type = 'mc' AND response_domain = 'Safety'")

unique_indicators <- unique(dd_filter$variable)

knitr::opts_chunk$set(echo = FALSE)
#### Step 3: Run Loop Funcion to produce tables ####
for (var_string in unique_indicators) {

  dict <- dd_filter %>% filter(variable == var_string) %>%
    pivot_longer(cols = response_1: response_12,
                 names_to = "responses",
                 values_to = paste0(var_string, "_labels"),
                 values_drop_na = TRUE)

  dict_var <- dict %>%
    mutate(variable_merge_col = 1:nrow(dict))


  df_var <- as_survey(svy_data, weights = weights_final) %>%
    group_by(!!rlang::ensym(var_string)) %>%
    summarise(frequency = n()) %>%
    mutate(percent = round(frequency/sum(frequency)*100, 1))

  df_final <-  merge(x = df_var, y = dict_var, by.x = c(var_string), by.y = c("variable_merge_col")) %>%
    relocate(paste0(var_string, "_labels")) %>% select(1, 3:8)

  visual <- print(kable(as.data.frame(df_final), "html") %>%
  kable_styling("striped", full_width = F) %>%
  row_spec(0, background = "#5E17EB", color = "white"))

  print(visual) 

}

```

```{r, echo=FALSE}
dbDisconnect(con)
```
