---
title: Correlation Analysis by Subcomponent and Component  
subtitle: Bold Vision Youth Thriving Survey 2024
author: Catalyst California in collaboration with Bold Vision
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(RPostgreSQL)
library(sf)
library(tidyr)
library(tidyverse)
library(srvyr)
library(survey)
library(knitr)
library(kableExtra)
library(weights)
library(corrplot)
library(Hmisc)
options(scipen=999)

# connect to postgres and pull credentials
source("W:\\RDA Team\\R\\credentials_source.R")
con <- connect_to_db("bold_vision")

dt_avg_scores <- dbGetQuery(con, "SELECT * FROM youth_thriving.avg_scores") %>%
rename( 'Positive Emotions' = "positiveemotions_sc_score",
'Self Efficacy' = "selfefficacy_sc_score",
'Hope for the Future' = "hopeforthefuture_sc_score",
'Growth Mindset' = "growthmindset_sc_score",
'Psychological Distress' = "psychologicaldistress_sc_score",
'Sparks' = "sparks_sc_score", #WILL NOT INCLUDE LATER BECAUSE THERE IS A HIGH NUMBER OF NAs 
'Relationships & Support' = "relationshipssupport_sc_score",
'Freedom to Explore Self' = "freedomtoexploretheself_sc_score",
'Connectedness' = "connectedness_sc_score",
'Critical Action' = "criticalaction_sc_score",
'Access to Public Spaces' = "safeaccesstopublicspaces_sc_score",
'Cultural Identity & Connection' = "culturalidentityandconnection_sc_score",
'Experiences of Racism' = "experiencesofracismanddiscrimination_sc_score",
'Microaggressions' = "microaggressions_sc_score",
'Structural Racism' = "structuralracism_sc_score",
'Personal Safety' = "personalsafety_sc_score",
'Strong Minds' = "strongminds_comp_score",
'Positive Identity & Self Worth' = "positiveidentityandselfworth_comp_score",
'Caring Families & Relationships' = "caringfamiliesandrelationships_comp_score",
'Vibrant Communities' = "vibrantcommunities_comp_score",
'Cultural Identity' = "culturalidentity_comp_score",
'Racial Justice, Equity, & Inclusion' = "racialjusticeequityandinclusion_comp_score",
'Safety' = "safety_comp_score"
)

##Colors

gray <- "#D6D7D6"
pink <- "#F75EC1"
dark_pink <- "#EF4A66"
orange <- "#F57E20"
yellow <- "#FFBF00"
light_green <- "#00A75A"
dark_green <- "#00864A"
blue  <- "#2A12B2"
light_blue <- "#465adc"
```

## By Subcomponent 

```{r, fig.width=8, fig.height=8}
dt_select <-  dt_avg_scores %>%
  # order columns by component
  select('Positive Emotions',
'Growth Mindset',
'Psychological Distress',
'Self Efficacy',
'Hope for the Future',
# 'Sparks', too many NAs
'Freedom to Explore Self',
'Critical Action',
'Relationships & Support',
'Connectedness',
'Access to Public Spaces',
'Personal Safety',
'Experiences of Racism',
'Microaggressions',
'Structural Racism',
'Cultural Identity & Connection') %>%
drop_na() # drop observations with NA

# # Custom colors for the group headers
# group_colors <- c(dark_pink, pink, yellow, dark_green, light_blue, blue, light_green)
# 
# # Create a grouping vector for headers/dividers
# groups <- c(
#   rep("Strong Minds", 3),         # Group 1
#   rep("Positive Identity & Self Worth", 5),           # Group 2
#   rep("Caring Families & Relationships", 2), # Group 3
#   rep("Vibrant Communities", 1), # Group 4
#   rep("Cultural Identity", 1),         # Group 5
#   rep("Racial Justice, Equity, & Inclusion", 3),          # Group 6
#   rep("Safety", 1) # Group 7 
# )

# Compute Spearman correlation matrix (no need to reorder dt_select here)
mydata.cor2 = cor(dt_select, method = "spearman")

# Statistical significance test for correlations
testRes2 = cor.mtest(dt_select, method = "spearman", conf.level = 0.95, exact = FALSE)

# Assign colors to variables according to their group directly
# We will match the color based on the group the variable belongs to

# # Create a vector of colors for each label
# group_colors_assigned <- unlist(lapply(groups, function(x) rep(group_colors[which(unique(groups) == x)], length.out = sum(groups == x))))

# Define a custom color ramp
custom_colors <- colorRampPalette(c("#b35806", "#542788"))

corrplot(
  mydata.cor2,
  type = 'full',
  col = custom_colors(300),
  p.mat = testRes2$p,
  insig = 'blank',
  diag = FALSE,
  tl.col = c(dark_pink,dark_pink, dark_pink, pink,pink,pink,pink,yellow, yellow,dark_green, light_green, blue, blue, blue, light_blue), # Apply the custom group colors to the text labels
  addgrid.col = "black" # Add grid lines to emphasize group separation
)


# store data in a dataframe
flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    var_1 = rownames(cormat)[row(cormat)[ut]],
    var_2 = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}
res_m<-rcorr(as.matrix(dt_select)) # run correlation matrix again
corr_df_sc<-flattenCorrMatrix(res_m$r, res_m$P)

```

## By Component
```{r, fig.width=8, fig.height=8}
dt_select <-  dt_avg_scores %>%
  select('Strong Minds',
'Positive Identity & Self Worth',
'Caring Families & Relationships',
'Vibrant Communities',
'Safety',
'Racial Justice, Equity, & Inclusion',
'Cultural Identity') %>%
drop_na() # drop observations with NA


mydata.cor2 = cor(dt_select, method="spearman")

testRes2 = cor.mtest(dt_select, method="spearman", conf.level = 0.95,exact=FALSE)

# Define a custom color ramp
custom_colors <- colorRampPalette(c("#b35806", "#542788"))

corrplot(
  mydata.cor2,
  type = 'full',
  col = custom_colors(300),
  p.mat = testRes2$p,
  insig = 'blank',
  diag = FALSE,
  tl.col = c(dark_pink,pink,yellow, dark_green, light_green, blue, light_blue), # Apply the custom group colors to the text labels
  addgrid.col = "black" # Add grid lines to emphasize group separation
)


# store data in a dataframe
res_m<-rcorr(as.matrix(dt_select)) # run correlation matrix again
corr_df_comp<-flattenCorrMatrix(res_m$r, res_m$P)


```

## By Demographics

### Race by Subcomponents 

```{r, fig.width=8, fig.height=8}
dt_race <-  dbGetQuery(con, "SELECT * FROM youth_thriving.race_ethnicity_data") 

dt_race_bipoc <- dt_race %>% 
  select(response_id, nh_race,race_black, race_aian_indigenous, race_latinx, race_asian, race_swana, race_nhpi, race_white) %>% 
  mutate(bipoc = ifelse(nh_race == 'nh_white', 0, 1))%>% # make anyone who is not non-Hispanic White alone, BIPOC
  select(-nh_race)%>%
  rename('BIPOC'='bipoc',
         'Black'='race_black',
         'AIAN'='race_aian_indigenous', 
         'Latine'='race_latinx', 
         'Asian'='race_asian', 
         'SWANA'='race_swana', 
         'NHPI'='race_nhpi', 
         'White'='race_white')

dt_join <- left_join(dt_avg_scores, dt_race_bipoc, by = "response_id")

dt_select <-  dt_join %>%
  select('BIPOC',
         'Black',
         'AIAN', 
         'Latine', 
         'Asian', 
         'SWANA', 
         'NHPI', 
         'White',
          'Positive Emotions',
          'Growth Mindset',
          'Psychological Distress',
          'Self Efficacy',
          'Hope for the Future',
        # 'Sparks', too many NAs
          'Freedom to Explore Self',
          'Critical Action',
          'Relationships & Support',
          'Connectedness',
          'Access to Public Spaces',
          'Personal Safety',
          'Experiences of Racism',
          'Microaggressions',
          'Structural Racism',
          'Cultural Identity & Connection') %>%
          drop_na()


# Compute Spearman correlation matrix (no need to reorder dt_select here)
mydata.cor2 = cor(dt_select, method = "spearman")

# Statistical significance test for correlations
testRes2 = cor.mtest(dt_select, method = "spearman", conf.level = 0.95, exact = FALSE)

# Define a custom color ramp
custom_colors <- colorRampPalette(c("#b35806", "#542788"))

corrplot(
  mydata.cor2,
  type = 'full',
  col = custom_colors(300),
  p.mat = testRes2$p,
  insig = 'blank',
  diag = FALSE,
  # addCoef.col = 'black',
  # col = COL2('PuOr', 10),
  tl.col = c("black", "black", "black", "black", "black", "black", "black","black", dark_pink,dark_pink, dark_pink, pink,pink,pink,pink,yellow,yellow, dark_green, light_green,blue, blue, blue, light_blue), # Apply the custom group colors to the text labels
  addgrid.col = "black" # Add grid lines to emphasize group separation
)

# store data in a dataframe
res_m<-rcorr(as.matrix(dt_select)) # run correlation matrix again
corr_df_race_sc<-flattenCorrMatrix(res_m$r, res_m$P)

```

### Race by Components 

```{r, fig.width=8, fig.height=8}

dt_select <-  dt_join %>%
  select('BIPOC',
         'Black',
         'AIAN', 
         'Latine', 
         'Asian', 
         'SWANA', 
         'NHPI', 
         'White',
          'Strong Minds',
          'Positive Identity & Self Worth',
          'Caring Families & Relationships',
          'Vibrant Communities',
         'Safety',
          'Racial Justice, Equity, & Inclusion',
          'Cultural Identity') %>%
 drop_na()


# Compute Spearman correlation matrix (no need to reorder dt_select here)
mydata.cor2 = cor(dt_select, method = "spearman")

# Statistical significance test for correlations
testRes2 = cor.mtest(dt_select, method = "spearman", conf.level = 0.95, exact = FALSE)

# Define a custom color ramp
custom_colors <- colorRampPalette(c("#b35806", "#542788"))

corrplot(
  mydata.cor2,
  type = 'full',
  col = custom_colors(300),
  p.mat = testRes2$p,
  insig = 'blank',
  diag = FALSE,
  # addCoef.col = 'black',
  # col = COL2('PuOr', 10),
  tl.col = c("black", "black", "black", "black", "black", "black", "black","black",dark_pink, pink, yellow, dark_green, light_green, blue, light_blue), # Apply the custom group colors to the text labels
  addgrid.col = "black" # Add grid lines to emphasize group separation
)

# store data in a dataframe
res_m<-rcorr(as.matrix(dt_select)) # run correlation matrix again
corr_df_race_comp<-flattenCorrMatrix(res_m$r, res_m$P)


```



### Other Demographics by Subcomponents 

```{r, fig.width=8, fig.height=8}

dt_gender <- dbGetQuery(con, "SELECT response_id, cishet_lgbtqia FROM youth_thriving.gender_sexuality_data") %>%
  rename(LGBTQIA = cishet_lgbtqia) 

otherdemos <- dbGetQuery(con, "SELECT response_id, q24,q25, q26, q27, q28 FROM youth_thriving.raw_survey_data") 

dt_otherdemos <- otherdemos%>%
   mutate_at(vars(q24:q28), .funs=list(
     ~case_when(
       .==1 ~ 1,
       .==2 ~ 0,
       .>=3 ~ NA,
       TRUE ~ NA)))%>%
  rename('Systems Impacted' = q24,
         'Detained/Arrested' = q25,
         'Suspended' = q26 ,
         'Undocumented' = q27 ,
         'Unhoused' = q28 ) %>% 
  select('response_id', 'Systems Impacted',
         'Detained/Arrested',
         'Suspended',
         'Undocumented',
         'Unhoused') 

dt_join <- left_join(dt_avg_scores, dt_gender, by = "response_id") 

dt_join_2 <- left_join(dt_join, dt_otherdemos, by = "response_id") 

dt_select <-  dt_join_2 %>%
  select('LGBTQIA',
         'Systems Impacted',
         'Detained/Arrested',
         'Suspended',
         'Undocumented',
         'Unhoused',
          'Positive Emotions',
          'Growth Mindset',
          'Psychological Distress',
          'Self Efficacy',
          'Hope for the Future',
          # 'Sparks', too many NAs
          'Freedom to Explore Self',
          'Critical Action',
          'Relationships & Support',
          'Connectedness',
          'Access to Public Spaces',
         'Personal Safety',
          'Experiences of Racism',
          'Microaggressions',
          'Structural Racism',
           'Cultural Identity & Connection') %>%
   drop_na()


# Compute Spearman correlation matrix (no need to reorder dt_select here)
mydata.cor2 = cor(dt_select, method = "spearman")

# Statistical significance test for correlations
testRes2 = cor.mtest(dt_select, method = "spearman", conf.level = 0.95, exact = FALSE)

# Define a custom color ramp
custom_colors <- colorRampPalette(c("#b35806", "#542788"))

corrplot(
  mydata.cor2,
  type = 'full',
  col = custom_colors(300),
  p.mat = testRes2$p,
  insig = 'blank',
  diag = FALSE,
  # addCoef.col = 'black',
  # col = COL2('PuOr', 10),
  tl.col = c("black", "black", "black", "black", "black", "black", dark_pink,dark_pink, dark_pink, pink,pink,pink,pink, yellow,yellow, dark_green, light_green, blue, blue, blue, light_blue), # Apply the custom group colors to the text labels
  addgrid.col = "black" # Add grid lines to emphasize group separation
)

# store data in a dataframe
res_m<-rcorr(as.matrix(dt_select)) # run correlation matrix again
corr_df_other_sc<-flattenCorrMatrix(res_m$r, res_m$P)

```

### Other Demographics by Components 

```{r, fig.width=8, fig.height=8}

dt_select <-  dt_join_2 %>%
  select('LGBTQIA',
         'Systems Impacted',
         'Detained/Arrested',
         'Suspended',
         'Undocumented',
         'Unhoused',
          'Strong Minds',
          'Positive Identity & Self Worth',
          'Caring Families & Relationships',
          'Vibrant Communities',
          'Safety',
          'Racial Justice, Equity, & Inclusion',
          'Cultural Identity') %>%
   drop_na()


# Compute Spearman correlation matrix (no need to reorder dt_select here)
mydata.cor2 = cor(dt_select, method = "spearman")

# Statistical significance test for correlations
testRes2 = cor.mtest(dt_select, method = "spearman", conf.level = 0.95, exact = FALSE)

# Define a custom color ramp
custom_colors <- colorRampPalette(c("#b35806", "#542788"))

corrplot(
  mydata.cor2,
  type = 'full',
  col = custom_colors(300),
  p.mat = testRes2$p,
  insig = 'blank',
  diag = FALSE,
  # addCoef.col = 'black',
  # col = COL2('PuOr', 10),
  tl.col = c("black", "black", "black", "black", "black", "black",dark_pink, pink, yellow, dark_green, light_green, blue, light_blue), # Apply the custom group colors to the text labels
  addgrid.col = "black" # Add grid lines to emphasize group separation
)

# store data in a dataframe
res_m<-rcorr(as.matrix(dt_select)) # run correlation matrix again
corr_df_other_comp<-flattenCorrMatrix(res_m$r, res_m$P)


```


```{r, include=FALSE, echo=FALSE}
# export to postgres

corr_sc_c<-rbind(corr_df_sc%>%mutate(level='Subcomponents'),
               corr_df_comp%>%mutate(level='Components'))


# dbWriteTable(con, c('youth_thriving', 'corr_analysis_components'), corr_sc_c,
#              overwrite = FALSE, row.names = FALSE)
# 
# dbSendQuery(con, paste0("COMMENT ON TABLE youth_thriving.corr_analysis_components IS '(Created on ", Sys.Date(),") The following is a table of correlation analysis and the outputs run  across subcomponent (referred to as variable name in data dictionary) 
# and across component (referred to as response domain in data dictionary). Learn more about the methodology here: W:\\Project\\OSI\\Bold Vision\\Youth Thriving Survey\\Documentation\\QA_correlation_analysis.docx';
# "))
# 
# dbSendQuery(con, "COMMENT ON COLUMN youth_thriving.corr_analysis_components.var_1 IS 'variable of interest';
#                   COMMENT ON COLUMN youth_thriving.corr_analysis_components.var_2 IS 'comparable variable of interest';
#                   COMMENT ON COLUMN youth_thriving.corr_analysis_components.cor IS 'the correlation value defines the strength and directin of the linear relationship between var_1 and var_2. A correlation value below 0.3 is generally considered weak and one of greater than 0.7 is considered strong. A positive value indicates that as one variable increase so does the other. A negative value indicates that as one variable increases, the other decreases.';
#                   COMMENT ON COLUMN youth_thriving.corr_analysis_components.p IS 'the p value measures the statistical significance of the output. A number less than 0.05 indicates a starticially significant correlation and anything greater than 0.05 is believed the relationship can be due to random chance.';
#                   COMMENT ON COLUMN youth_thriving.corr_analysis_components.level IS 'indicates what type of variables are being measured';
#             ")

race<-c('BIPOC','Black','Latine','Asian','SWANA','NHPI','White','AIAN')

corr_sc_c_race<-rbind(corr_df_race_sc%>%mutate(level='Race and Subcomponents'),
               corr_df_race_comp%>%mutate(level='Race and Components'))%>%
              filter(var_1 %in% race | var_2 %in% race)


# dbWriteTable(con, c('youth_thriving', 'corr_analysis_race'), corr_sc_c_race,
#              overwrite = FALSE, row.names = FALSE)
# 
# dbSendQuery(con, paste0("COMMENT ON TABLE youth_thriving.corr_analysis_race IS '(Created on ", Sys.Date(),") The following is a table of correlation analysis and the outputs run by race groups, subcomponents (referred to as variable name in data dictionary) 
# and components (referred to as response domain in data dictionary). Learn more about the methodology here: W:\\Project\\OSI\\Bold Vision\\Youth Thriving Survey\\Documentation\\QA_correlation_analysis.docx';
# "))
# 
# dbSendQuery(con, "COMMENT ON COLUMN youth_thriving.corr_analysis_race.var_1 IS 'variable of interest';
#                   COMMENT ON COLUMN youth_thriving.corr_analysis_race.var_2 IS 'comparable variable of interest';
#                   COMMENT ON COLUMN youth_thriving.corr_analysis_race.cor IS 'the correlation value defines the strength and directin of the linear relationship between var_1 and var_2. A correlation value below 0.3 is generally considered weak and one of greater than 0.7 is considered strong. A positive value indicates that as one variable increase so does the other. A negative value indicates that as one variable increases, the other decreases.';
#                   COMMENT ON COLUMN youth_thriving.corr_analysis_race.p IS 'the p value measures the statistical significance of the output. A number less than 0.05 indicates a starticially significant correlation and anything greater than 0.05 is believed the relationship can be due to random chance.';
#                   COMMENT ON COLUMN youth_thriving.corr_analysis_race.level IS 'indicates what type of variables are being measured';
#             ")

other<-c('LGBTQIA',
         'Systems Impacted',
         'Detained/Arrested',
         'Suspended',
         'Undocumented',
         'Unhoused')

corr_sc_c_other<-rbind(corr_df_other_sc%>%mutate(level='Other Demographics and Subcomponents'),
               corr_df_other_comp%>%mutate(level='Other Demographics and Components'))%>%
                filter(var_1 %in% other | var_2 %in% other)


# dbWriteTable(con, c('youth_thriving', 'corr_analysis_demographics'), corr_sc_c_other,
#              overwrite = FALSE, row.names = FALSE)
#   
# dbSendQuery(con, paste0("COMMENT ON COLUMN youth_thriving.corr_analysis_demographics IS '(Created on ", Sys.Date(),") The following is a table of correlation analysis and the outputs run by demographic variables (LGBTQIA, Systems Impacted, Detained/Arrested, Suspended, Undocumented, Unhoused), subcomponents (referred to as variable name in data dictionary) 
# and components (referred to as response domain in data dictionary). Learn more about the methodology here: W:\\Project\\OSI\\Bold Vision\\Youth Thriving Survey\\Documentation\\QA_correlation_analysis.docx';
# "))
# 
# dbSendQuery(con, "COMMENT ON COLUMN youth_thriving.corr_analysis_demographics.var_1 IS 'variable of interest';
#                   COMMENT ON COLUMN youth_thriving.corr_analysis_demographics.var_2 IS 'comparable variable of interest';
#                   COMMENT ON COLUMN youth_thriving.corr_analysis_demographics.cor IS 'the correlation value defines the strength and directin of the linear relationship between var_1 and var_2. A correlation value below 0.3 is generally considered weak and one of greater than 0.7 is considered strong. A positive value indicates that as one variable increase so does the other. A negative value indicates that as one variable increases, the other decreases.';
#                   COMMENT ON COLUMN youth_thriving.corr_analysis_demographics.p IS 'the p value measures the statistical significance of the output. A number less than 0.05 indicates a starticially significant correlation and anything greater than 0.05 is believed the relationship can be due to random chance.';
#                   COMMENT ON COLUMN youth_thriving.corr_analysis_demographics.level IS 'indicates what type of variables are being measured';
#             ")

dbDisconnect(con)

```